name = "GROQ"
grammar = "groq"
path_suffixes = ["groq"]
line_comments = ["// "]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true }
]
